add_subdirectory(mpmc_mutable_msg)
add_subdirectory(mpmc_mutable_msg_2)
add_subdirectory(mpmc_redirect)
add_subdirectory(mpmc_remove_consumers)
add_subdirectory(mpmc_root_only)
add_subdirectory(mpmc_several_consumers)
add_subdirectory(mpsc_redirect)
add_subdirectory(mpsc_root_only)
add_subdirectory(mpsc_several_consumers_1)
add_subdirectory(mpsc_several_consumers_2)
add_subdirectory(mpsc_simple)
add_subdirectory(node_as_root)
add_subdirectory(simple)
