add_subdirectory(agent_without_activity)
add_subdirectory(cancel_delayed_msg)
add_subdirectory(cancel_periodic_msg)
add_subdirectory(empty_init_fn)
add_subdirectory(simple_delayed_msg)
add_subdirectory(simple_exec_order)
add_subdirectory(simple_periodic_msg)
add_subdirectory(simplest_agent)
add_subdirectory(stats_coop_count)
add_subdirectory(stats_on)
add_subdirectory(stats_wt_activity)

add_subdirectory(stress_timers)

add_subdirectory(unknown_exception_init_fn)
add_subdirectory(unknown_exception_init_fn_2)
add_subdirectory(unknown_exception_init_fn_3)

add_subdirectory(completion_on_stop)
