add_subdirectory(illegal_usage)
add_subdirectory(simple)
add_subdirectory(simple_enveloped_msg)
add_subdirectory(simple_for_each)
add_subdirectory(simple_for_each_enveloped_msg)
add_subdirectory(simple_for_each_with_index)
add_subdirectory(simple_mutable)
add_subdirectory(simple_mutable_for_each)
add_subdirectory(simple_mutable_for_each_enveloped_msg)
add_subdirectory(simple_mutable_for_each_with_index)
add_subdirectory(simple_n)
add_subdirectory(simple_n_signal)
add_subdirectory(simple_signal)
add_subdirectory(with_nth_noncopyable_ref)
